# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
sitename: Maukasta.fi
title: Maukasta - Ruokablogi jossa opit nautit ja herkuttelet mauakkaista jututista.
email: andreas.koutsoukos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruokablogi josta löytää helposti etsimänsä reseptin tai ruoka-aiheisen artikkelin. 
  Soppia keittelee Andreas joka on entinen ravintola kokki joka harrastaa nykyisin ruokakulttuuria ja sisällön tekmistä ruoan parissa. Tule mukaan oppimaan, nauttimaan ja herkuttelemaan.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.maukasta.fi" # the base hostname & protocol for your site
twitter_username: maukastafi
github_username:  vjandrei

# Build settings
markdown: kramdown

comments: true

timezone: Europe/Helsinki

exclude: ['node_modules', 'gulpfile.js', 'Gemfile', 'Gemfile.lock', 'Capfile', 'config', 'lib', 'REVISION']

gems: ['jekyll-lunr-js-search']

lunr_search:
  excludes: [rss.xml, atom.xml]
  stopwords: "stopwords.txt"
  min_length: 3
  js_dir: "js"
 
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

facebook_app_id: 706459809385922

collections:
- yhteistyot